name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - name: Create `environment.ts`
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: false," >> src/environments/environment.ts
          echo "   apiUrl: '${{ secrets.BACKEND_API_URL}}'," >> src/environments/environment.ts
          echo "  firebaseConfig: {" >> src/environments/environment.ts
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/environments/environment.ts
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> src/environments/environment.ts
          echo "    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> src/environments/environment.ts
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> src/environments/environment.ts
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> src/environments/environment.ts
          echo "    appId: '${{ secrets.FIREBASE_APP_ID }}'," >> src/environments/environment.ts
          echo "    measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> src/environments/environment.ts
          echo "  }" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Replace Environment Variables in `environment.prod.ts`

        run: |
          sed -i "s|apiUrl: ''|apiUrl: '${{ secrets.BACKEND_API_URL }}'|" src/environments/environment.prod.ts
          sed -i "s|apiKey: ''|apiKey: '${{ secrets.FIREBASE_API_KEY }}'|" src/environments/environment.prod.ts
          sed -i "s|authDomain: ''|authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'|" src/environments/environment.prod.ts
          sed -i "s|projectId: ''|projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'|" src/environments/environment.prod.ts
          sed -i "s|storageBucket: ''|storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'|" src/environments/environment.prod.ts
          sed -i "s|messagingSenderId: ''|messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'|" src/environments/environment.prod.ts
          sed -i "s|appId: ''|appId: '${{ secrets.FIREBASE_APP_ID }}'|" src/environments/environment.prod.ts
          sed -i "s|measurementId: ''|measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'|" src/environments/environment.prod.ts

      - run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREATIVE_HUB_8D4DA }}
          channelId: live
          projectId: creative-hub-8d4da
        continue-on-error: true
